language: node_js

node_js:
 - "8"
 - "10"
 - "12"

branches:
  only:
    - master

services:
 - mongodb

install:
 - npm install

before_install:
 - npm update -q

before_script:
  - npm run lint

after_script:
  # Trigger only one coverage file
  - if [ "$TRAVIS_NODE_VERSION" = "10" ]; then npm run test:coveralls; fi
